// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzFXQIwa7hrfU4jVtLklSPknIBg6fmZAw',
    appId: '1:973193697170:web:30691b6b9622b75513d34b',
    messagingSenderId: '973193697170',
    projectId: 'adcommerce-notification',
    authDomain: 'adcommerce-notification.firebaseapp.com',
    storageBucket: 'adcommerce-notification.firebasestorage.app',
    measurementId: 'G-CTQRBHHJCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJD24KhIYz2wEw_JHgGCdnsb1OE6XXQCc',
    appId: '1:973193697170:android:3658ef6ef9ef34f313d34b',
    messagingSenderId: '973193697170',
    projectId: 'adcommerce-notification',
    storageBucket: 'adcommerce-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBusfKJ3Iw0bmJDZN0SCGFltfkfpbIyK2E',
    appId: '1:973193697170:ios:112e77cab0dbe8ab13d34b',
    messagingSenderId: '973193697170',
    projectId: 'adcommerce-notification',
    storageBucket: 'adcommerce-notification.firebasestorage.app',
    iosBundleId: 'com.aerstore.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBusfKJ3Iw0bmJDZN0SCGFltfkfpbIyK2E',
    appId: '1:973193697170:ios:af3244ec65becf7e13d34b',
    messagingSenderId: '973193697170',
    projectId: 'adcommerce-notification',
    storageBucket: 'adcommerce-notification.firebasestorage.app',
    iosBundleId: 'com.example.adECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzFXQIwa7hrfU4jVtLklSPknIBg6fmZAw',
    appId: '1:973193697170:web:3dcab00d04cf808313d34b',
    messagingSenderId: '973193697170',
    projectId: 'adcommerce-notification',
    authDomain: 'adcommerce-notification.firebaseapp.com',
    storageBucket: 'adcommerce-notification.firebasestorage.app',
    measurementId: 'G-P2Y6XJWKBP',
  );
}
